language: c++
env:
  global:
    - MAKEFLAGS=-j3
services:
  - docker    
# By default travis loads submodules serially, but we can load them in parallel
# if we install an updated git and use --jobs.  Some timing numbers:
#   serial: 257s
#   jobs=4: 182s (29s to install new git, 153s to run the downloads)
#   jobs=8: 179s (29s to install new git, 150s to run the downloads)
# We can't use --depth=1, though, because github doesn't have
# allowReachableSHA1InWant set.
#
# TODO(jefftk): once we're running on a server with git 2.8 or later we can have
#               --jobs without installing a new git.
git:
  submodules: false
before_install:
  - docker build docker/alpine-3.8/nginx-mainline/
  - docker build docker/alpine-3.8/nginx-stable/  
  - docker build docker/alpine-edge/nginx-mainline/ 
  - docker build docker/alpine-edge/nginx-stable/ 
  - sudo add-apt-repository --yes ppa:git-core/ppa
  - sudo apt-get update
  - sudo apt-get install git
  - git submodule update --init --recursive --jobs=8
install:
  scripts/build_ngx_pagespeed.sh --devel --assume-yes
script:
  test/run_tests.sh $PWD/testing-dependencies/mod_pagespeed/ \
                    $PWD/nginx/sbin/nginx
dist: trusty
sudo: required
compiler:
  - gcc
notifications:
  email:
    - pagespeed-ci@googlegroups.com
